### ISSUE TITLE
Text Block To Mark Conditions In Miniatures

### ISSUE THREAD

**Issue by shortyhero** [Bouncyrock/TaleSpire-Beta-AssetRequests#119]
**Describe the Asset**
Ability to put a visible text block on top of miniatures to show current conditions in battle.

**Example**
![D0byJ43WwAIViN7](https://user-images.githubusercontent.com/63584616/89101340-fecf2980-d3cc-11ea-932a-f6c69f78bbd1.jpg)

**Additional context**
Sometimes is hard to track combat, specially with spells and conditions, stuff like concentration, buffs and debuffs. It would be nice to have an option to create a simple shaped block that you can insert text.

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
The devs are already working on an emote system that should handle these things (last we've heard about it, they were planning on having small 2D images hovering next to a mini - there's actually a scene in the Kickstarter trailer where this is visible). Apart from that I'd say that this is not really an asset request but more a feature request overall, so I'll close this issue
