### ISSUE TITLE
Tile request, flat roof tiles

### ISSUE THREAD

**Issue by FearedNightmare** [Bouncyrock/TaleSpire-Beta-AssetRequests#12]
**Describe the Asset**
A horizontal version of the current roof tiles

**Examples (images, videos, something which gets the point across**
N/A

**Additional context**
Right now there's no way to finish the roof of a building without using some random tiles from a different set that don't match

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Got added in the latest update
