### ISSUE TITLE
Cat / Feline humanoid race

### ISSUE THREAD

**Issue by jectordelan** [Bouncyrock/TaleSpire-Beta-AssetRequests#121]
At some point, we'll need cat races as they show up in various games under numerous names: Kzinti, Caitian, Tabaxi, Aslan, etc. We just need a bipedal, feline based race, preferably with digitigrade legs. 

https://i.pinimg.com/originals/c1/27/c5/c127c5a85c2385b3f6b38a992bc28a1a.jpg

The werewolf should make an easy base to convert to felinoid. Swap the head, narrow the tail, and dress it up.

** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
last update added two catfolk minis.
