### ISSUE TITLE
 Spiritual weapon mini

### ISSUE THREAD

**Issue by Alarn777** [Bouncyrock/TaleSpire-Beta-AssetRequests#127]
**Describe the Asset**
Special mini for Spiritual weapon

**Examples (images, videos, something which gets the point across**
![1322338](https://user-images.githubusercontent.com/33755705/91631546-fe817880-e9e2-11ea-896e-de649df4ad50.jpg)

**Additional context**
Just the simple transparent mini like this one.

 ADD :thumbsup:[thumbs up reaction] to give this request more attention

**Comment by jectordelan** [comment]
We have one of these now. Magic weapon (hammer) in the Constructs section.

**Comment by LuPro** [comment]
As jector said, it's in the game now :)
