### ISSUE TITLE
Kenku, or Corvidian, or something like that.

### ISSUE THREAD

**Issue by ZcytheGaming** [Bouncyrock/TaleSpire-Beta-AssetRequests#129]
**Describe the Asset**
What does it look like, how is it used. Paint us a figurative picture.
Short hunched over long raven beak, no wings and bird like feet. Often depicted as roguish.

**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.
![image](https://user-images.githubusercontent.com/72701210/95682949-dffbc900-0bad-11eb-94f9-eba754b9007d.png)
![image](https://user-images.githubusercontent.com/72701210/95682955-e8ec9a80-0bad-11eb-91cc-c657365a5e5a.png)

**Additional context**
Unburden yourself of thoughts and musings here

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by pyrestriker** [comment]
I was just coming here to also suggest this. I just had to use an Imp to represent our Aarakocra player. I felt horrible.

**Comment by LuPro** [comment]
We got a Ravenfolk (aka Kenku) mini in the last update! 🎉
