### ISSUE TITLE
Fog of war

### ISSUE THREAD

**Issue by mefgengus** [Bouncyrock/TaleSpire-Beta-AssetRequests#141]
**Describe the Asset**
What does it look like, how is it used. Paint us a figurative picture.

I know work is in progress...but,seen some of your old vids on it!....just an idea,how about it stays solid and foggy like.. but as the figures move close and through it it melts away...each figure has a invisible barrier around it .could be a standard radius or custom for each figure...and if the figure is wounded it gets smaller..blocking his view making it more vulnerable as its wounded.....and if they all stay close to each other the melting radius has a larger field of view....in rooms the walls ,floors,ceilings,and any type of openings block the radius view ..out side the sky and the ground have no fog...anyway .just an idea.you probably have it sorted...just love the game....
**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.

**Additional context**
Unburden yourself of thoughts and musings here

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
This is not an asset request, it's best to put this in the feature request channel of the Discord - but as you said, they are already working on it anyways :)
