### ISSUE TITLE
Cut and paste

### ISSUE THREAD

**Issue by mefgengus** [Bouncyrock/TaleSpire-Beta-AssetRequests#142]
**Describe the Asset**
What does it look like, how is it used. Paint us a figurative picture.
The white cut and paste box,would be great if it had tile dimensions on it ,height,width,and length...indicating the amount of tiles....reason for this is to double check for slab size....and if it was made too big ....rather counting all the tiles ..you could read them and slice the work up into equal sizes......so that they fit the slab and then be numbered...to rejoin them ,...less room for errors...
**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.

**Additional context**
Unburden yourself of thoughts and musings here

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Please drop that in #feature-requests in the discord, that's a better place for this - here it should stay strictly to asset (tiles, props, minis) requests
