### ISSUE TITLE
Slabs

### ISSUE THREAD

**Issue by mefgengus** [Bouncyrock/TaleSpire-Beta-AssetRequests#144]
**Describe the Asset**
What does it look like, how is it used. Paint us a figurative picture.
Oh me again....would it be possible to have  a build time length indicator with the information on the slab,would be interesting and maybe helpful for the down loader...
As they may like the slap and want to build one ,but not have the time to..so quicker to copy and down load.......or if not with the slabs,but with the build menu,some builds are so large,,it would be like wow ...how long!and fun to know.....

**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.

**Additional context**
Unburden yourself of thoughts and musings here

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Same as my earlier comment, info on talesbazaar/tavern is nothing the devs can do and that's not strictly an asset request
