### ISSUE TITLE
Slab counter 

### ISSUE THREAD

**Issue by mefgengus** [Bouncyrock/TaleSpire-Beta-AssetRequests#145]
**Describe the Asset**
What does it look like, how is it used. Paint us a figurative picture.
Might be fun if the slabs had a counter that indicated the amount of times a slab was down loaded...would show the builders that they are on the write track.....

**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.

**Additional context**
Unburden yourself of thoughts and musings here

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by mefgengus** [comment]
Ah yeah sorry found it

**Comment by LuPro** [comment]
If this is feedback for talestavern/talesbazaar, please keep in mind that those are made by the community and not by the devs, so nothing they can do about that. also keep in mind that this is for *asset* requests and thus is not really an asset :)
