### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by mefgengus** [Bouncyrock/TaleSpire-Beta-AssetRequests#147]
**Describe the Asset**
What does it look like, how is it used. Paint us a figurative picture.
Ok small bug....think I came across one....cow skull.....if stacked,clipped and rotated......it seems it won’t delete,or be moved....have tried to reload,and redo steam....but it/they still stay......is very minor

**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.

**Additional context**
Unburden yourself of thoughts and musings here

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by ShaunDave** [comment]
Hi @mefgengus , this repo is for new asset requests, not bugs...
There is a public beta issue tracker repo here: https://github.com/Bouncyrock/TaleSpire-Beta-Public-Issue-Tracker

**Comment by LuPro** [comment]
As shaun said, since you already posted there I'll close this :)
