### ISSUE TITLE
Tents (Camping, War Camp, Circus)

### ISSUE THREAD

**Issue by Stormshot64** [Bouncyrock/TaleSpire-Beta-AssetRequests#16]
![images](https://user-images.githubusercontent.com/65003689/81371774-9f9f9880-90ad-11ea-8e64-ee896afe99db.jpg)
![images (1)](https://user-images.githubusercontent.com/65003689/81371778-9f9f9880-90ad-11ea-97b2-fed524060f58.jpg)
![download](https://user-images.githubusercontent.com/65003689/81371779-a0382f00-90ad-11ea-8aed-1b1f06c154a1.jpg)
![images (2)](https://user-images.githubusercontent.com/65003689/81371780-a0382f00-90ad-11ea-8976-a34d2dbec3b6.jpg)
![images (3)](https://user-images.githubusercontent.com/65003689/81371781-a0382f00-90ad-11ea-8b0c-af04345775a2.jpg)
![Tent-1](https://user-images.githubusercontent.com/65003689/81371782-a0d0c580-90ad-11ea-8903-7ee2f858ed1c.jpg)
![6996-130](https://user-images.githubusercontent.com/65003689/81371783-a0d0c580-90ad-11ea-98e4-028f45d08f6a.jpg)
![Yakima-Tent-Civil-War-Wall-Tent-1](https://user-images.githubusercontent.com/65003689/81371784-a1695c00-90ad-11ea-81a8-f8a89d317392.jpg)

Camping Tents (wedge tents) - Small Triangular Prisms that can fit in either one tile or 2x2 tiles, probably small enough to be a single building feature without an interior, cliche style tents for a single adventurer or traveler, canvas exterior with small bits of rope and wood stakes for detail, perhaps could even be slightly modified with holes to show a damaged tent.
War Camp Tent (safari tent) - Assets for wall and roof tiles of canvas: straight corners and quarter-circle corners, as well as "sagging" curved roof tiles. Potential for "damaged" variations with wholes in the fabric. 
Circus Tent - Similar in assets to the War Camp Tent, but with striped colors (or by offering 2 color variations for each piece, can create our own stripes during building).

** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by jonnyree** [comment]
Single tents will be added in an update soon. Modular tents will be added in a later update.

**Comment by jonnyree** [comment]
Closing this as we added tents in the Merchant Expansion set. Will make more variants in the future. Thanks for the suggestions!
