### ISSUE TITLE
Missing Asset after Chimera: Castle Stone Table

### ISSUE THREAD

**Issue by ShaunDave** [Bouncyrock/TaleSpire-Beta-AssetRequests#168]
It seems that the large castle stone table isn't available in the new props after the Chimera update.
Example:
![image](https://user-images.githubusercontent.com/63476710/113325972-61404700-9319-11eb-9b2b-c2d12616817f.png)

**Comment by jectordelan** [comment]
This is back in now, although it isn't handled like a prop yet.

**Comment by ShaunDave** [comment]
This is sorted, thanks!
