### ISSUE TITLE
Wall hanging Mirrors various Sizes 

### ISSUE THREAD

**Issue by Funggiss** [Bouncyrock/TaleSpire-Beta-AssetRequests#207]
I look good in this armor. Is it just a mirror or is it door? How did that cast a mirror that large it must be magic. Is that someone standing behind me?

Having the mirror be functional in game would be cool but I don't know if that is over complicated just a grey space would work.

<br>**ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
We have a (small) variety of mirrors now! If you feel like there's still something crucial missing submit a new issue and tell us why you think there's another mirror missing, I'll close this now.
