### ISSUE TITLE
Condition/effect icons

### ISSUE THREAD

**Issue by atibas2112** [Bouncyrock/TaleSpire-Beta-AssetRequests#208]
I would really love some way to show current conditions and effects on a token (frightened, poisoned, paralyzed etc.). Something both the GM and the players could keep track of. Something like this:

![Captura de tela 2021-04-25 191954](https://user-images.githubusercontent.com/83188977/116011413-451f8500-a5fb-11eb-8ba7-72e57c0ca5a8.png)

<br>**ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Not really an asset request, but a feature request. Devs are aware of this need and have plans for it.
