### ISSUE TITLE
Tracing forms to represent continuous spells

### ISSUE THREAD

**Issue by atibas2112** [Bouncyrock/TaleSpire-Beta-AssetRequests#209]
I know you can trace the area of effect of spells, but sometimes there are spells that affect an area for more than one turn (for instance, casting Grease, Moonbean or Fog Cloud in DnD 5e. Would be great to be able to trace those areas and have them 'stick' to the board, representing which tiles/area the spell is affecting. You could then drag it around, just like a token, if the spell is being moved (by the user in the case of Moonbeam or with the user in the case of Spirit Guardians, for instance).

<br>**ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Devs are planning on making persistent rulers that would help mark areas for longer periods of time that would work for highlighting longer lasting spell effects - not really an asset request, but a feature request so more for the feature request channel on the discord (the devs are however already aware of this need, so no need to add it again)
