### ISSUE TITLE
Dwarf tiles, hero variety, and cavalry

### ISSUE THREAD

**Issue by Huli-ts** [Bouncyrock/TaleSpire-Beta-AssetRequests#214]
Dwarven architecture tiles ( dwarf pls!)

Large flightless bird for domestic animals ( perhaps with saddle)
Cavalry minis for the heroic races, goblns on wolves/spiders, orcs on boars
Heroic race variety ( a few more felne, lizardfolk, frog variants) currently feels human/elf centric .More dwarves?!)
<br>**ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Dwarven tiles have already been requested here: #156
The bird request is at least somewhat related to #138, but more specific/overall a bit different.
The heroic mini request is a bit vague, but I get the gist of the request.

As a side note: In the future please request each thing in its own issue so votes can be gathered for individual requests and individual requests can be closed once implemented. For this time I'll make individual issues myself.

**Comment by LuPro** [comment]
Large flightless bird as domestic animals (perhaps with saddle)

**Comment by LuPro** [comment]
Cavalry minis for the heroic races, goblins on wolves/spiders, orcs on boars

**Comment by LuPro** [comment]
Non-Human Heroic race variety
A few more feline, lizardfolk, frog variants, ...

**Comment by Huli-ts** [comment]
Apologies it's the first time i've used github or made asset requests. I'll make sure to go individual and more specific next time.
Thank you

**Comment by LuPro** [comment]
No worries - it's not a platform people outside of development regularly use, so it's not unexpected to have some "getting used to it" issues here and there :)
