### ISSUE TITLE
Make Moorgoth Roof Set tile with itself

### ISSUE THREAD

**Issue by Istallri** [Bouncyrock/TaleSpire-Beta-AssetRequests#22]
**Describe the Asset**
Currently moorgoth roof do not tile with itself, showing the repetition - not sure if intended

**Examples (images, videos, something which gets the point across**
![image](https://user-images.githubusercontent.com/65011758/81406711-66f9d080-913a-11ea-90cd-0a408e4ab6b3.png)

** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
I believe this has been fixed, I'll close it. If my eyes deceived me and it still is relevant, please add a comment saying so, so I can reopen the issue
