### ISSUE TITLE
DND 5E PHB p.#: 145, 146, 149, 150, 151, 153, 154

### ISSUE THREAD

**Issue by ugly2632** [Bouncyrock/TaleSpire-Beta-AssetRequests#223]
**Describe the Asset**
All of the items listed in the DND 5E PHB p.#: 146, 145, 149, 150, 151, 153, 154 in one form or another can be added to the list. This includes Adventuring kits, weapons, armour, items... If you're lost on what to put in, those pages are a good start.

**Examples (images, videos, something which gets the point across)**
DND 5E PHB p.#: 146, 145, 149, 150, 151, 153, 154

**Additional context**
DND 5E PHB p.#: 146, 145, 149, 150, 151, 153, 154

<br>**ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by ugly2632** [comment]
Just go through the tables.

**Comment by LuPro** [comment]
Not going through the individual pages now, I presume on there are minis and props; in the future please go for a bit more focused requests (as this is mostly "overall more content please" instead of "from all the things you could be adding, I'd wish for this specifically")

**Comment by ugly2632** [comment]
> 
> 
>  instead of "from all the things you could be adding, I'd wish for this specifically")

OK sounds good.
