### ISSUE TITLE
Enhancement: Locked-axis &  precise movement of a selected volume

### ISSUE THREAD

**Issue by paul-king** [Bouncyrock/TaleSpire-Beta-AssetRequests#224]
As a map builder, I would like the ability to select a volume of tiles and move them along a specified axis (x, y, z) 1 tile at a time. This is similar to how assets can be moved in 3D programs by holding a key that corresponds to the axis on which the selected volume is 'locked'. Ideally, this would include a visual indication of which axis to which movement has been constrained.
 
As an additional enhancement, the number of tiles I would like to shift the selected volume by could be specified. For example: move the selected block of tiles "up" [z-index] by 4 and "back" [x- or y-index] by 2 spaces.

**Comment by LuPro** [comment]
Not an asset request, but a feature request; please post this in the #feature-request channel on the [discord](https://discord.gg/talespire). (If you don't have discord/don't want to join I can post your request there for the devs to see)

**Comment by paul-king** [comment]
Will do. Thanks!
