### ISSUE TITLE
Wide dirt path retexture/tiles

### ISSUE THREAD

**Issue by Lioki909** [Bouncyrock/TaleSpire-Beta-AssetRequests#233]
**Description**:

There is currently a selection of tiles for 1 tile wide dirt path, but when you want to make a larger path for town and cities or grassless areas without making it look like a desert, you can only use the crossroad dirt tiles that lets very visible and perpendicular patches of grass everywhere. Those little patches of grass drive me mad wherever I see them. This would need a set of new borders and full dirt tiles to work but I think it's ultimately worth it for a single road type.

Current wide dirt path:

![dirt1](https://user-images.githubusercontent.com/84389067/118657266-9cc0a300-b7eb-11eb-91a9-dc5fe544fdaa.png)

Upgraded wide dirt path:

![dirt2](https://user-images.githubusercontent.com/84389067/118657299-a64a0b00-b7eb-11eb-96a6-e6d2c185ed1b.png)

SO SMOOTH

<br>**ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Duplicate/Extension of #6
