### ISSUE TITLE
Real benches and props for tables

### ISSUE THREAD

**Issue by Keksader** [Bouncyrock/TaleSpire-Beta-AssetRequests#25]
**Describe the Asset**
Benches that look like someone could sit at and props like papers or swords that sit on the tables instead of just floating off on the side.

**Examples (images, videos, something which gets the point across**
![image](https://user-images.githubusercontent.com/63508698/81422319-cd71f500-9120-11ea-877a-63586c6b00c7.png)
![image](https://user-images.githubusercontent.com/63508698/81422457-f85c4900-9120-11ea-8b41-f7365700ac62.png)

**Additional context**
Right now we only have benches that are smaller than some floor tiles and the not props that sit right on tables, everything just kind of floats off of the side.

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
A bunch of the props previously tied to tables are now free to use on their own and this together with the new prop system allows for some variety in seating - I'll close this for now, if you feel like there's still a great lack of benches/chairs, please comment so I can reopen or make a new issue explaining what exactly is still missing (What I'm noticing is that there's a lack of "fancy" benches/chairs for example)

PS: a list of seating options currently available
![image](https://user-images.githubusercontent.com/20774976/121578264-c788ca80-ca2a-11eb-8dba-b7f05cf08ee5.png)
