### ISSUE TITLE
1x1 tables and chairs, and 'table snapping'

### ISSUE THREAD

**Issue by jayy00** [Bouncyrock/TaleSpire-Beta-AssetRequests#26]
so many premade campaigns will have tables and chairs in small spaces, now in talespire to recreate some of these, you have to use the only sized table which has to collide with the walls in order to work in some cases, or reduce the number of tables. Personally, the option for smaller tables and to place them without snapping to the grid would be fantastic, along with allowing chairs to snap to the edge of the table rather than merely snapping to the grid like other objects
![Full100060_b72ceb7b14d9342f01ae96fbe5a0da83](https://user-images.githubusercontent.com/62804401/81423860-090dbe80-9123-11ea-9660-f0051048d57f.jpg)
![thumbnail_493bcd36-2433-4df1-9ab3-cd37458fc9e2 png 2048x2048_q85](https://user-images.githubusercontent.com/62804401/81423862-09a65500-9123-11ea-958a-515600e9a31b.jpg)
I feel like this would allow for map recreation to be done with far more ease, also this may have been mentioned before, but allow for pieces to sit in a seat at a table or onto benches. Hope I can see this come into the game, and thank you for everything so far!

**Comment by lebion** [comment]
It would be nice to have the actual table's items a version without chairs and individual chairs though

**Comment by LuPro** [comment]
With the new prop system this should be pretty much solved. If there's still something missing, please create a new issue explaining what you'd wish to see in addition to that
