### ISSUE TITLE
Thatched roof styles

### ISSUE THREAD

**Issue by Stasisdelirium** [Bouncyrock/TaleSpire-Beta-AssetRequests#31]
Just a simple request for thatched roof tiles for a more 'rustic' look of a village.  Both rough and the 'sheared' types.

Some examples:

![thatched1](https://user-images.githubusercontent.com/65038092/81435014-5fc7c800-9124-11ea-9ea2-baa934ea4cca.jpg)

![thatched2](https://user-images.githubusercontent.com/65038092/81435038-67876c80-9124-11ea-948c-43c43e0c1943.jpg)

This could also include 'mossy' style roof tiles or even roof tiles that have damage/holes in them (ruined town roof tiles?).  Something akin to:

![moss1](https://user-images.githubusercontent.com/65038092/81435137-91d92a00-9124-11ea-91cf-4bcaab6586a9.jpg)

Just a few ideas for spicing up roof tiles for towns etc.

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
This has been added a while ago
