### ISSUE TITLE
Stair and ladder sets

### ISSUE THREAD

**Issue by Skitzat** [Bouncyrock/TaleSpire-Beta-AssetRequests#32]
**Describe the Asset**
Stairs that are automatically one floor in height. Possible variants include wooden or stone. Options with railings or spiral staircases would be a plus. 

Ladders that can snap to a wall or be free standing. Alignment would ideally be at the end of tile.

**Examples (images, videos, something which gets the point across**
Ladder
![image](https://user-images.githubusercontent.com/65038367/81435149-373bd000-911c-11ea-9705-213a1d401084.png)
Ladder with hatch
![image](https://user-images.githubusercontent.com/65038367/81435212-54709e80-911c-11ea-858e-8333ded10f66.png)

Stairs
Railing
![image](https://user-images.githubusercontent.com/65038367/81435342-8eda3b80-911c-11ea-9472-9ac2efd10ce8.png)
Spiral
![image](https://user-images.githubusercontent.com/65038367/81435387-a6b1bf80-911c-11ea-8b72-74729c7a7297.png)
Stair blocks that turn
![image](https://user-images.githubusercontent.com/65038367/81435439-bcbf8000-911c-11ea-863f-9509943a5b10.png)

**Additional context**
Currently building stairs is tedious. Wall height stairs would expedite building. Additional skin/colors would benefit immersion into worlds. Spiral staircases would reduce floor usage while adding vertical elements to maps. 

Ladders would also help adding vertical elements without committing a lot of ground tiles to stairs. Thematically they fit certain environments like barns and trap doors better than stairs.

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by Skitzat** [comment]
I know ladders were mentioned by another user, but I wanted to add further focus beyond the sparse details in their post.

**Comment by dontbemadb-rad** [comment]
Ladders could also be used against terrain (boulders?). Would certainly be helpful for building forts, guard towers...

**Comment by LuPro** [comment]
the stair idea feels similar to #29, I like the ladders idea though

**Comment by Skitzat** [comment]
> the stair idea feels similar to #29, I like the ladders idea though

My apologies on the lazy search. I had searched for "stairs" so I missed "stairwells" and "staircases".

**Comment by Wrexverdi** [comment]
Corner stairs would be great as well.  RH and LH orientation, and stairs that fit in a corner when I have a setup like this, where the blocks are: 
![20200509115504_1](https://user-images.githubusercontent.com/65079368/81478507-fc08d200-91eb-11ea-8db7-14914d3e0632.jpg)

**Comment by lebernstein** [comment]
Absolutely need spiral staircases. Most likely in a 10' square footprint.

**Comment by ShaunDave** [comment]
We have some nice ladders already, but spiral staircases are a bit of a pain right now... Having a few different spiral stairwell diameters would be ideal... From a super-tight 2-block-diameter set to more open 6-block-diameter tower staircases:
![image](https://user-images.githubusercontent.com/63476710/103780244-6739cb00-503d-11eb-8d3a-e9e5c18b3ec1.png)

If possible, a huge 20-block-diameter spiral set would allow vast towers with yawning chasms in the middle...
![image](https://user-images.githubusercontent.com/63476710/103780310-7f114f00-503d-11eb-92cf-766b52f313ea.png)
