### ISSUE TITLE
Larger miniatures ( 2x1, 2x2 or even 3x3)

### ISSUE THREAD

**Issue by Sendery** [Bouncyrock/TaleSpire-Beta-AssetRequests#34]
**Describe the Asset**
Larger creatures
I play some games that the creatures are 2x1, 2x2 or even 3x3 and I do miss some really big monster to face off,

**Examples (images, videos, something which gets the point across**
![74947259_598258384313096_4962562547412755357_n 1](https://user-images.githubusercontent.com/10600957/81454050-7fdea200-918b-11ea-99b3-5a0d51ccfd4d.jpg)

**Additional context**
I couldnt make work the resize feature yet, and I understand if this wasnt plan on advance. managing the mineatures collisions probably will have to be rethink in order to make this happend. But Im sorry the ice giant or the dragon asset are a little bit to small for my taste .

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Miniature scaling is already planned and as far as I know exists in internal prototypes. Once that is in, some minis will probably have other default sizes (some that are larger by default or smaller by default)

**Comment by LuPro** [comment]
As creature scaling is now added into the game I'll close this :)
