### ISSUE TITLE
Blue Foam

### ISSUE THREAD

**Issue by jerb835** [Bouncyrock/TaleSpire-Beta-AssetRequests#37]
**Describe the Asset**
I would like to get blue foam to put down until we get water. 

**Examples (images, videos, something which gets the point across**
You know... like the green foam... but blue.

**Additional context**
I just thought that during the development phase of things while we dont have water assets, it would be nice to be able to denote water and such with blue foam so we can do water that way instead.

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Tiles that serve as a placeholder for the planned water system are already planned as far as I know, though we don't know yet when we will see them
