### ISSUE TITLE
Stackable Internal or External Chimney Structure

### ISSUE THREAD

**Issue by jlormes** [Bouncyrock/TaleSpire-Beta-AssetRequests#42]
**Describe the Asset**

The current hearth for the Tavern looks great, but there's no continuation of the chimney stack to connect the base hearth upwards through the frame. When the structure is open, or there's a central hearth there needs to be a way to extend that hearth structure upwards to show continuity. Something like a wall panel that continues the chimney upwards would be sufficient for the current Tavern Fireplace wall/floor asset, but I'd also like to see a free standing (non-wall) hearth for builds that have the fireplace (or even an oven) in a more central location.

On the external side, having a substantial chimney that runs up the side of a building adds realism and some opportunities for potentially climbing or gameplay.

**Examples (images, videos, something which gets the point across**

In the example below from the 1700's the chimney/hearth is a substantial/central part of the house. This is common among timber framed buildings and would be a neat atmospheric to be able to implement.

![image](https://user-images.githubusercontent.com/6827275/81484489-bbbd4a00-9213-11ea-9d9b-a7c26daedaa5.png)

source: http://www.iongdw.com/multipage/Cape-May-text.pdf

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
![image](https://user-images.githubusercontent.com/20774976/106076772-82fe3180-6110-11eb-9ef5-d8ec81f2e1d7.png)
Could use more variety, but it is a stackable chimney! I'll close this for now, if you think there's something more that should be added, please create a new issue (unless you think this does not fulfill the request, in which case it would be nice to hear what you think should be different about it so I can reopen the issue)

**Comment by jlormes** [comment]
This will work I think. It’ll also look nice in an open setting where the fireplace is in the middle of the room in say a large open tavern.

**Comment by jlormes** [comment]
I haven’t had a chance to try it, but having this stack on top of the existing internal fireplace would be good if it doesn’t already.

**Comment by LuPro** [comment]
Currently not at the computer anymore but I think to get this to mesh with the fireplace prop you'd probably need some work with clipping, though I think it should be possible
