### ISSUE TITLE
External Wooden Access Stairs

### ISSUE THREAD

**Issue by jlormes** [Bouncyrock/TaleSpire-Beta-AssetRequests#43]
**Describe the Asset**

A set of wood frame stairs to provide access to external doors on the upper floors of building. Up until a certain period it was very uncommon for the ground and 1st floors to be internally connected by stairs. Most often there was an external staircase that led up to an external door on the first floor. That's why on many older buildings you sometimes see doors on an upper story that appear to me leading to nowhere. The internal staircase was added as a feature later in life of the building. 

Sometimes a stone staircase just doesn't fit with an all timber building.

**Examples (images, videos, something which gets the point across**

![image](https://user-images.githubusercontent.com/6827275/81484702-c4af1b00-9215-11ea-8291-885faa0c42c8.png)
source: https://upload.wikimedia.org/wikipedia/commons/7/74/Rosheim_maison_romane.jpg

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
![image](https://user-images.githubusercontent.com/20774976/106077416-cb6a1f00-6111-11eb-9d1d-d04918fc070e.png)
Not quite made for this (meant to be indoors stairs), however I personally feel this works rather well for this application - would this satisfy your request or would you like something more specific to your example? I'll leave the issue open for now.

**Comment by jlormes** [comment]
I think that this will work just fine. There’s no specific set of features for these...so a set of wooden stairs that will attach to the outside and provide a landing is a good simple solution.
