### ISSUE TITLE
Western assets for the game

### ISSUE THREAD

**Issue by Whomp28** [Bouncyrock/TaleSpire-Beta-AssetRequests#44]
**Describe the Asset**
What does it look like, how is it used. Paint us a figurative picture.

I was thinking it would be cool for the game to have western assets (tiles and creatures). Creating those "rusty old towns" which are mostly made out of wood in the desert (to give you an idea of what I'm talking about) as well as bigger and more modern cities like Saint Denis in Read Dead 2. As for the creatures, well, a variety of minis representing most of the jobs there were (cowboys/girls, priests and nuns, bandits, banker, bartender, etc) as well as wild animals like coyotes, puma and all was what I was thinking about.

**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.

Here is a picture of what I was thinking when I said "rusty old town"
https://i.pinimg.com/originals/5a/03/a5/5a03a528bae24b828b93524038952adc.jpg

**Additional context**
Unburden yourself of thoughts and musings here

I'm proposing this because I haven't seen the devs or anyone else talking about doing it and I know that Cyberpunk assets will be a thing, so I thought "why not having more universes to play with ?" and immediately thought about western.

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by mesclin** [comment]
It would be awesome to play some Deadlands in Talespire!

**Comment by Whomp28** [comment]
I know right ? To be honest I was thinking more about Tecumah Gulch.

**Comment by LuPro** [comment]
![image](https://user-images.githubusercontent.com/20774976/106077942-ceb1da80-6112-11eb-9bdd-c269ad90c85b.png)
I think more variety would be needed, but this, together with parts of the tavern set, a few castle brick walls and merchant stalls could do the trick for some western style areas - I'd close this issue as the "general feel" for a rural / western-ish town can be captured with this, if you want to request more specific things for this setting, please open another issue - if you think my screenshot doesn't really work for this kind of style, please comment and I'll open the issue again
