### ISSUE TITLE
Beaches and other water land fronts

### ISSUE THREAD

**Issue by EHCM81** [Bouncyrock/TaleSpire-Beta-AssetRequests#47]
**Describe the Asset**

Beaches (I looked but didn't see any posts about this).

Beaches, sand, ocean, ocean with fish, sharks, shallow beach waters, docks, rocky beach fronts, beach cliff sides, stormy waters and rough seas, crashing waves, typhoon and vortexes, hot spots and steamy waters, hammocks, and pirate themed beach related props as well.

Some props I can think of are Crabs, fish nets, docks, skulls, a kraken lol, squids, coconuts, sea gulls and other animals found near ocean fronts.

Some other water meeting land tile ideas: mangroves, cattails, wetlands, salt marshes, other estuary's, and other unmentioned water and land related meeting points. 

**Examples (images, videos, something which gets the point across**

<img src="https://myhawaiibeachfront.com/wp-content/uploads/2013/12/Kauai-1018x460.jpg">

<img src="https://media-cdn.tripadvisor.com/media/photo-s/01/76/d2/7e/one-of-2-beach-fronts.jpg">

<img src="https://santacruzlife.com/wp-content/uploads/2013/05/natural-bridges-beach.jpg">

<img src="https://cdn.vox-cdn.com/thumbor/7buuOwucJNxC0_SLVHuqC7dHIuQ=/0x0:5616x3744/1200x900/filters:focal(2359x1423:3257x2321):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/63894275/shutterstock_1216608706.0.jpg">

<img src="https://www.aquaaston.com/files/live/sites/aah/files/destinations/kona-coast/kona-coast-hawaii-island-hero-1-beach-767x520.jpg">

<img src="https://www.land-links.org/wp-content/uploads/2016/12/mangrove-work-banner.png">

<img src="https://www.yaleclimateconnections.org/pics/cc/mc/051719_salt_marsh.jpg">

<img src="https://www.iucn.org/sites/dev/files/content/images/2018/okavango_deltaciucn_peter_howard.jpg">

**Additional context**
I know this isn't a prop or tile, but rain environment. Light, medium, heavy, and hurricane and typhoon like conditions. Also, lightning ranging from intensity to regularity, to proximity.

Last one, I promise, a sky box and the ability to have the camera be more first person-esque? I was running a campaign in a cavern with tight spaces and the party really wanted to see things from ground level more in the vein of first person... Just passing on their suggestions.

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
There's been a bunch of things added to help build beaches:
![image](https://user-images.githubusercontent.com/20774976/121581279-f2c0e900-ca2d-11eb-9419-add3466bc68f.png)

Additionally to what's shown on the screenshot there's a bunch of harbor tiles with nets, fishing poles, there's reeds, water lily's and more in that direction.
I'll close this issue, but if you have some more specific requests, feel free to create a new issue with that
