### ISSUE TITLE
Traps and secrets 

### ISSUE THREAD

**Issue by CaffeeNated** [Bouncyrock/TaleSpire-Beta-AssetRequests#5]
**Describe the Asset**
A set of tiles that look like regular tiles from other packs (more specifically the dungeon/castle/morgoth tile sets, with the major addition of it being able to open and/or activate

that being secret doors can open on the walls and trap doors can open underneath figures.

this would also include things like Arrow dispensers like from Indiana jones, or spike traps, pit falls, wall spikes, pendulum traps and other such traps that could activate after doing something, such as entering an area or steping on a specific "trap tile activator"

**Examples (images, videos, something which gets the point across**
![image](https://user-images.githubusercontent.com/64992797/81352604-53cf0c80-910a-11ea-9807-22f6d6858db1.png)
![image](https://user-images.githubusercontent.com/64992797/81352640-61849200-910a-11ea-9fb7-c6a17f81ba40.png)
![image](https://user-images.githubusercontent.com/64992797/81352703-85e06e80-910a-11ea-92ee-07f0787cb3b8.png)
![image](https://user-images.githubusercontent.com/64992797/81352752-a3153d00-910a-11ea-955b-c65dc3b73747.png)
![image](https://user-images.githubusercontent.com/64992797/81352807-cc35cd80-910a-11ea-8723-12cdc3babf49.png)
![image](https://user-images.githubusercontent.com/64992797/81352946-26cf2980-910b-11ea-8520-ac0a127d46f9.png)

**Additional context**
I would imagine they would work something like either normal doors a hatches(for the secret doors) or automatic tiles that would activate when stepped on, not all traps need to be made, but I would still like the classics, the trap door to spikes/pit fall, floor spikes and secret doors

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by Paul-herrera** [comment]
I think someone on the dev team has addressed secret wall doors, but at least having spiked tiles to place at the bottom of pits would be great!

**Comment by jonnyree** [comment]
We've got a traps update coming up next month.

**Comment by mefgengus** [comment]
Tapestries would be good to hide doors

**Comment by mefgengus** [comment]
Ok secret doors.....awhile back came across a bug,opened a door and there was another,,,but looking back that actually would work,for an never ending magical door...also would be good,I presume the secret doors will be of the same effect as walls,etc...so what would be good,to have a shimmer door over lay which now and then gives the door away,as not to miss an opportunity,and work of the secret,,plus it could be placed on walls so that it gave the illusion of one being there,and also takes the expectation of one actually being there away

**Comment by LuPro** [comment]
There's now all of these traps as well as a handful of hatches/trap doors, so I'd close this issue as implemented and if there's some more *specific* traps you'd like to see, please create new issues for those
![image](https://user-images.githubusercontent.com/20774976/121569226-d79bac80-ca20-11eb-8d85-d6be138d513f.png)
