### ISSUE TITLE
Water tiles

### ISSUE THREAD

**Issue by justinas-marozas** [Bouncyrock/TaleSpire-Beta-AssetRequests#52]
**Describe the Asset**

Water tiles in a similar manner road tiles are done.

**Examples (images, videos, something which gets the point across**

<img width="274" alt="Screenshot 2020-05-11 at 22 07 45" src="https://user-images.githubusercontent.com/7419290/81611927-dccc9900-93d3-11ea-970b-6922f12cd3c9.png">

<img width="703" alt="Screenshot 2020-05-11 at 22 08 30" src="https://user-images.githubusercontent.com/7419290/81611998-f837a400-93d3-11ea-82e6-7eb416b7d26b.png">

**Additional context**

I want to dig a ditch around my castle!

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
Duplicate of #3
