### ISSUE TITLE
Wooden Palisade Walls, Heavy Doors, and Towers

### ISSUE THREAD

**Issue by orangejuiceOMFG** [Bouncyrock/TaleSpire-Beta-AssetRequests#59]
Sharpened logs driven into the ground to form a crude wall. Ideal for bandit camps or remote trading outposts. 

![images (1)](https://user-images.githubusercontent.com/65237437/81705088-3f558180-9434-11ea-9851-3084edd33105.jpeg)

![440px-Museumdorf_Düppel2](https://user-images.githubusercontent.com/65237437/81705587-d02c5d00-9434-11ea-84d0-a8754b677ee9.jpeg)

**Additional context**
Unburden yourself of thoughts and musings here

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by sheehanicy** [comment]
i would love this!
