### ISSUE TITLE
Merchant stalls

### ISSUE THREAD

**Issue by Sargatas** [Bouncyrock/TaleSpire-Beta-AssetRequests#68]
**Describe the Asset**
Merchant stalls, for open markets/bazaars.  

**Examples (images, videos, something which gets the point across**
![d745654a0916fb216ebbc952edcf9176--medieval-market-medieval-weapons](https://user-images.githubusercontent.com/30532431/81955191-c7c05780-95d7-11ea-8e2a-a0f88b615f2f.jpg)
![70cc16a4ec0265ce96bcee48d9cba1c6](https://user-images.githubusercontent.com/30532431/81955204-ca22b180-95d7-11ea-95e3-f5e0abb9f208.jpg)

**Additional context**
Part of my main city in my homebrew world is a market in the poor section of town, were adventures can find things not generally sold in stores, direct from the docks, etc.  Not quite The Bazaar on Deva, but almost as bad/good ;) "if you think you've gotten a good deal from a Deveel, first count your fingers, then your limbs, then your relatives"

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by 42stinger** [comment]
That would be lovely, although if you need something quickly give this a try https://talesbazaar.com/prefab/1064

**Comment by demongund** [comment]
I think this was addressed in a recent asset update.

**Comment by jonnyree** [comment]
Closing this because the Merchant Expansion set. Thanks for the suggestions!
