### ISSUE TITLE
Glowy magical crystals

### ISSUE THREAD

**Issue by Skittles88** [Bouncyrock/TaleSpire-Beta-AssetRequests#78]
**Describe the Asset**
Various sized magical crystals that emit a glow for ambience. IE: Dark magical crystal, Tiberium crystals, luminescent gemstones etc.

**Examples (images, videos, something which gets the point across**
![image](https://user-images.githubusercontent.com/65439499/82112864-602e1780-9751-11ea-9cc8-ecad527d8689.png)

![image](https://user-images.githubusercontent.com/65439499/82112875-75a34180-9751-11ea-8c4c-a3a31f189c5a.png)

![image](https://user-images.githubusercontent.com/65439499/82112876-82c03080-9751-11ea-82e4-f7a30802672f.png)

**Additional context**

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by mesclin** [comment]
and fungi too!

**Comment by LuPro** [comment]
For now not in different colours, but the [latest booster pack](https://bouncyrock.com/news/articles/chilling-expedition-booster-pack) added glowy magical crystals! If you want more variation / something different please open another issue, I'll consider this closed for now :)
