### ISSUE TITLE
Bedroll

### ISSUE THREAD

**Issue by brcoding** [Bouncyrock/TaleSpire-Beta-AssetRequests#82]
**Describe the Asset**
What does it look like, how is it used. Paint us a figurative picture.

A blanket with ropes or belts tied around it.

A version with the blanket spread out on the floor would be good as well.

**Examples (images, videos, something which gets the point across**
Or show us a literal picture. That works too.

![image](https://user-images.githubusercontent.com/148889/82704208-e81c9180-9c29-11ea-9087-657b3e02fda6.png)

![image](https://user-images.githubusercontent.com/148889/82704295-14d0a900-9c2a-11ea-83b3-d140d46949e4.png)

**Additional context**
Unburden yourself of thoughts and musings here

This is used in D&D in every single room of a peasant / thugger / thief / peon, every campsite

-- Leave this next line for others to see --
** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by jonnyree** [comment]
This will be coming in an update soon.

**Comment by jonnyree** [comment]
Beta Asset update 02: The Campfire Tile Extension Set feature bedrolls :)

**Comment by LuPro** [comment]
Bedrolls got introduced, if you want expansion/changes on that open a new issue for that :)
