### ISSUE TITLE
Crystal Cavern Set and Props

### ISSUE THREAD

**Issue by Istallri** [Bouncyrock/TaleSpire-Beta-AssetRequests#88]
**Describe the Asset**
tiles with big crystals and made of crystal to make a crystral mine or crystal floor/walls

**Examples (images, videos, something which gets the point across**
![image](https://user-images.githubusercontent.com/65011758/83260278-c8511480-a1b9-11ea-8383-ed7f4fd14c3d.png)
![image](https://user-images.githubusercontent.com/65011758/83260378-f46c9580-a1b9-11ea-8097-4b65f47b7026.png)

** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
[Latest booster pack](https://bouncyrock.com/news/articles/chilling-expedition-booster-pack) added this - I'll close this issue now :)
