### ISSUE TITLE
Prop Alignment

### ISSUE THREAD

**Issue by BevedUpRose** [Bouncyrock/TaleSpire-Beta-AssetRequests#89]
While it can be nice that the props are placed in the center of single tiles, it can also be frustrating when a recreated map calls for a pillar to be at the junction of four single tiles.

![prop placement](https://user-images.githubusercontent.com/65508133/83337978-69f16800-a285-11ea-8e0f-1d45133e45ca.png)

The first red dot is how props currently align on the grid, I think it would be helpful if props and things like pillars could also align in the center.

** ADD :thumbsup:[thumbs up reaction] to give this request more attention.**

**Comment by LuPro** [comment]
This is not really an asset request, but more of a feature request - additionally such a system is already planned and internal prototypes already exist - it is planned to come soon(tm), which is why I'll close this issue :)
